const words=[{ word: "banana", hint: "Yellow fruit with a peel" },
    { word: "orange", hint: "A citrus fruit" },
    {word:"Mobile",hint:"Used to communicate with others"},
    { word: "elephant", hint: "Large mammal with a trunk" },
    { word: "computer", hint: "Electronic device for processing data" },
    { word: "guitar", hint: "Musical instrument with strings" },
    { word: "mountain", hint: "Tall landform often found with snow on top" },
    { word: "umbrella", hint: "Used to protect against rain or sun" },
    { word: "garden", hint: "Outdoor area with plants and flowers" },
    { word: "pizza", hint: "Popular Italian dish with cheese and toppings" },
    { word: "oxygen", hint: "Element essential for human respiration" },
    { word: "volcano", hint: "Mountain that erupts with lava and ash" },
    { word: "octopus", hint: "Sea creature with eight arms" },
    { word: "airplane", hint: "Aircraft used for air travel" },
    { word: "library", hint: "Place where books and other materials are kept" },
    { word: "sunshine", hint: "Bright light and warmth from the sky" },
    { word: "bicycle", hint: "Two-wheeled vehicle propelled by pedals" },
    { word: "television", hint: "Device for receiving and displaying broadcast signals" },
    { word: "sandwich", hint: "Food item consisting of bread with fillings" },

]